### ISSUE TITLE
Do we want "free" to remain as a public function?

### ISSUE THREAD

**Issue by lemire** [piotte13/SwiftRoaring#4]
What happens if the user calls "free" and then the object goes out of scope? Do you get two frees on the same pointer?

One way around that is to set the pointer to NULL as part of the free function. However, one should then document that the class is unsafe from that point forward (which might be fine *if* it is documented).

**Comment by piotte13** [comment]
Good point.
Setting the pointer to NULL as part of the free function could work, although I believe the end user should not be aware of the memory management since this is a swift version and we have a fantastic garbage collector!
For this reason, the "free" function will be set to private!
